### ISSUE TITLE
Incorrect password. Please try again.

### ISSUE THREAD

**Issue by shenloon** [AppFlowy-IO/AppFlowy-Cloud#1578]
Describe the bug
I'm unable to login on /console after fresh installation (git clone). When logging in using the GOTRUE_ADMIN_EMAIL and GOTRUE_ADMIN_PASSWORD from the .env configuration file, an error message appears: Incorrect password. Please try again

Request URL
https://note.yyyd.top/login

To Reproduce
Followed this guide:

https://appflowy.com/docs/Local-Host-Deployment
Expected behavior
Login properly to the admin console.

**Comment by appflowy** [comment]
@shenloon Can you try the latest docker images? It should be fixed

**Comment by titusse3** [comment]
still don't work, even in lastest version of the docker images.

**Comment by SrDayne** [comment]
In my case, switching to HTTPS scheme resolved the issue. Set `SCHEME=https` and `WS_SCHEME=wss` in .env.

**Comment by arthurpos** [comment]
Hello everyone,
This bug seems to be the same like #1588  and I managed to resolve it today.
The solution I used was to configure the FQDN as follows: <DOCKER_IP>:<MY_NGINX_PORT>
