### ISSUE TITLE
[Bug] It is not possible to open AppFlowy from the admin frontend web page

### ISSUE THREAD

**Issue by SilvioMessi** [AppFlowy-IO/AppFlowy-Cloud#956]
**Describe the bug**
After logging into the admin frontend and clicking on the "Open AppFlowy" icon, the application does not start, and the following error appears in the browser console:
`Access to XMLHttpRequest at 'appflowy-flutter://login-callback#access_token=<token>&expires_at=1730492952&expires_in=7200&refresh_token=<token>&token_type=bearer' (redirected from 'http://localhost/web-api/open_app') from origin 'http://localhost' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: chrome, chrome-extension, chrome-untrusted, data, http, https, isolated-app.`

**To Reproduce**
1. Follow the [deployment guidline](https://github.com/AppFlowy-IO/AppFlowy-Cloud/blob/main/doc/DEPLOYMENT.md) to run the AppFlowy server locally
2. Open the admin frontend [web page](http://localhost/web/login) 
3. Login
4. Click "Open AppFlowy" icon  
5. See error on the browser console 

**Expected behavior**
After logging into the admin frontend and clicking on the "Open AppFlowy" icon, the AppFlowy application should open.

**Screenshots**
![Screenshot from 2024-11-01 19-33-43](https://github.com/user-attachments/assets/403f1fe9-d11d-4264-8c9e-8fadd069d74a)

**Desktop (please complete the following information):**
 - Browser: Chrome and Firefox

**Additional context**
When using an older version of the admin frontend container (e.g. 0.6.25), this issue does not occur.

**Comment by owenyang0** [comment]
same

**Comment by SpringYear** [comment]
我也一样，希望能优先修复这个问题

**Comment by speed2exe** [comment]
@SilvioMessi @owenyang0 @SpringYear This should be fixed in the latest images, you can do `docker compose pull` to fetch the newest image, and then `docker compose up -d` to update

**Comment by pedroponte** [comment]
Problem persists with new pull

<img width="1286" alt="Screenshot 2024-12-04 at 19 54 59" src="https://github.com/user-attachments/assets/fc9e8717-6023-4cdb-a903-497ba96cc9d2">

**Comment by speed2exe** [comment]
@pedroponte You would need to have appflowy installed and have the your OS to register this scheme. If you have not install it, you may do so from the recommended channels (https://docs.appflowy.io/docs/appflowy/install-appflowy/installation-methods/mac-windows-linux-packages)

**Comment by hellokelli** [comment]
It is nearly a year later and I have this issue on the latest version as well.  I have tried with both web browser and with app installed through recommended channels. Of course the app gives me no error logging tools, it just does not work.

Also, the document here (https://appflowy.com/docs/self-host-appflowy-deploy-appflowy-cloud) appears outdated as it references a variable "$appflowy_web" in the nginx/nginx.conf that appears to no longer be used.  I am assuming it is now called $appflowy_web_backend, but could potentially be $admin_frontend_backend since that one has 3000 as a port. Clarification in this document could possibly solve the problem.
